ERROR - 2023-01-02 01:56:52 --> mysqli_sql_exception: Table 'khdtk.users' doesn't exist in D:\XAMPP\htdocs\KHDTK - experimental\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\XAMPP\htdocs\KHDTK - experimental\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `users`....', 0)
#1 D:\XAMPP\htdocs\KHDTK - experimental\vendor\codeigniter4\framework\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users`....')
#2 D:\XAMPP\htdocs\KHDTK - experimental\vendor\codeigniter4\framework\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users`....')
#3 D:\XAMPP\htdocs\KHDTK - experimental\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `users`....', Array, false)
#4 D:\XAMPP\htdocs\KHDTK - experimental\app\Controllers\DataUser.php(19): CodeIgniter\Database\BaseBuilder->get()
#5 D:\XAMPP\htdocs\KHDTK - experimental\vendor\codeigniter4\framework\system\CodeIgniter.php(927): App\Controllers\DataUser->index()
#6 D:\XAMPP\htdocs\KHDTK - experimental\vendor\codeigniter4\framework\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DataUser))
#7 D:\XAMPP\htdocs\KHDTK - experimental\vendor\codeigniter4\framework\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\XAMPP\htdocs\KHDTK - experimental\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\XAMPP\htdocs\KHDTK - experimental\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(46): require_once('D:\\XAMPP\\htdocs...')
#10 {main}
CRITICAL - 2023-01-02 01:56:52 --> Table 'khdtk.users' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `users`.`id` as `userid`, `username`, `email`, `fullname`, `created_at`, `active`, `name`
FROM `users`
JOIN `auth_groups_users` ON `auth_groups_users`.`user_id` = `users`.`id`
JOIN `auth_groups` ON `auth_groups`.`id` = `auth_groups_users`.`group_id`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users`.`id` as `userid`, `username`, `email`, `fullname`, `created_at`, `active`, `name`
FROM `users`
JOIN `auth_groups_users` ON `auth_groups_users`.`user_id` = `users`.`id`
JOIN `auth_groups` ON `auth_groups`.`id` = `auth_groups_users`.`group_id`')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users`.`id` as `userid`, `username`, `email`, `fullname`, `created_at`, `active`, `name`
FROM `users`
JOIN `auth_groups_users` ON `auth_groups_users`.`user_id` = `users`.`id`
JOIN `auth_groups` ON `auth_groups`.`id` = `auth_groups_users`.`group_id`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT `users`.`id` as `userid`, `username`, `email`, `fullname`, `created_at`, `active`, `name`
FROM `users`
JOIN `auth_groups_users` ON `auth_groups_users`.`user_id` = `users`.`id`
JOIN `auth_groups` ON `auth_groups`.`id` = `auth_groups_users`.`group_id`', [], false)
 5 APPPATH\Controllers\DataUser.php(19): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\DataUser->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DataUser))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-02 02:48:46 --> Undefined variable: inven
in APPPATH\Views\user-database\inven.php on line 539.
 1 APPPATH\Views\user-database\inven.php(539): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: inven', 'APPPATH\\Views\\user-database\\inven.php', 539, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\user-database\\inven.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('user-database/inven', [], true)
 5 APPPATH\Controllers\Auth.php(20): view('user-database/inven', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-02 02:48:57 --> Undefined variable: inven
in APPPATH\Views\user-database\inven.php on line 539.
 1 APPPATH\Views\user-database\inven.php(539): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: inven', 'APPPATH\\Views\\user-database\\inven.php', 539, [...])
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\user-database\\inven.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('user-database/inven', [], true)
 5 APPPATH\Controllers\Auth.php(20): view('user-database/inven', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-02 02:50:12 --> Invalid file: Myth\Auth\Views\_message_block.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('Myth\\Auth\\Views\\_message_block.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('Myth\\Auth\\Views\\_message_block', [], true)
 3 APPPATH\Views\auth\login.php(11): view('Myth\\Auth\\Views\\_message_block')
 4 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\auth\\login.php')
 5 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('auth/login', [], true)
 7 APPPATH\Controllers\Auth.php(20): view('auth/login', [...])
 8 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 9 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-02 02:50:17 --> Invalid file: Myth\Auth\Views\_message_block.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('Myth\\Auth\\Views\\_message_block.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('Myth\\Auth\\Views\\_message_block', [], true)
 3 APPPATH\Views\auth\login.php(11): view('Myth\\Auth\\Views\\_message_block')
 4 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\auth\\login.php')
 5 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 6 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('auth/login', [], true)
 7 APPPATH\Controllers\Auth.php(20): view('auth/login', [...])
 8 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 9 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2023-01-02 02:54:39 --> The route for "login" cannot be found.
in SYSTEMPATH\Helpers\url_helper.php on line 543.
 1 SYSTEMPATH\Helpers\url_helper.php(543): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute('login')
 2 APPPATH\Views\auth\login.php(12): url_to('login')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\auth\\login.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('auth/login', [], true)
 6 APPPATH\Controllers\Auth.php(20): view('auth/login', [...])
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->login()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
